//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class BST_STATISTICSEntities : DbContext
{
    public BST_STATISTICSEntities()
        : base("name=BST_STATISTICSEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<TESTREQUEST> TESTREQUESTS { get; set; }
    public virtual DbSet<FIPVERSION> FIPVERSIONs { get; set; }
    public virtual DbSet<PC> PCS { get; set; }
    public virtual DbSet<PERSON> PERSONS { get; set; }
    public virtual DbSet<BSTLOG> BSTLOGs { get; set; }
    public virtual DbSet<SCHEDULE> SCHEDULEs { get; set; }
}
